// Mock data used across admin and student pages

export const MOCK_STUDENTS = [
  { id: 'S001', name: 'Tanaka Hiroshi', email: 'tanaka@japanese.international', level: 'N3', intake: 'April 2024', status: 'Active', progress: 64, phone: '+94 77 111 2233', enrolled: '2024-04-01' },
  { id: 'S002', name: 'Kavindra Perera', email: 'kavindra@email.com', level: 'N2', intake: 'January 2024', status: 'Active', progress: 88, phone: '+94 71 223 4456', enrolled: '2024-01-15' },
  { id: 'S003', name: 'Dilrukshi Fernando', email: 'dilrukshi@email.com', level: 'N4', intake: 'July 2024', status: 'Active', progress: 42, phone: '+94 76 334 5567', enrolled: '2024-07-01' },
  { id: 'S004', name: 'Ruwan Silva', email: 'ruwan@email.com', level: 'N5', intake: 'September 2024', status: 'Inactive', progress: 15, phone: '+94 77 445 6678', enrolled: '2024-09-10' },
  { id: 'S005', name: 'Nadeeka Jayasinghe', email: 'nadeeka@email.com', level: 'N3', intake: 'April 2024', status: 'Active', progress: 71, phone: '+94 71 556 7789', enrolled: '2024-04-01' },
  { id: 'S006', name: 'Chamara Bandara', email: 'chamara@email.com', level: 'N2', intake: 'January 2024', status: 'Active', progress: 95, phone: '+94 78 667 8890', enrolled: '2024-01-10' },
  { id: 'S007', name: 'Priyanka Kumari', email: 'priyanka@email.com', level: 'N1', intake: 'April 2023', status: 'Graduated', progress: 100, phone: '+94 72 778 9901', enrolled: '2023-04-01' },
  { id: 'S008', name: 'Suresh Wijeratne', email: 'suresh@email.com', level: 'N5', intake: 'September 2024', status: 'Active', progress: 28, phone: '+94 77 889 0012', enrolled: '2024-09-15' },
]

export const MOCK_NOTIFICATIONS = [
  { id: 1, title: 'JLPT July 2025 Registration Open', body: 'Registration for the July 2025 JLPT exam is now open. Contact admin to register. Deadline: April 30, 2025.', date: '2025-03-10', type: 'exam', read: false },
  { id: 2, title: 'New Vacancy: Yamamoto Manufacturing', body: 'A new job vacancy for Production Line Operator at Yamamoto Manufacturing in Osaka has been posted. N4 level required. 8 seats available.', date: '2025-03-08', type: 'vacancy', read: false },
  { id: 3, title: 'April 2025 Intake Starting Soon', body: 'The April 2025 intake begins on April 7, 2025. Please ensure your enrollment is complete and fees are paid by April 1.', date: '2025-03-05', type: 'schedule', read: true },
  { id: 4, title: 'Mock Interview Sessions — March', body: 'Online mock interview practice sessions for March are scheduled every Saturday at 10:00 AM. Join via your student portal Zoom link.', date: '2025-03-01', type: 'event', read: true },
  { id: 5, title: 'New Video Lessons Added — N3 Grammar', body: 'Six new video lessons covering JLPT N3 grammar patterns (て-form, causative, passive) have been added to the student portal.', date: '2025-02-28', type: 'content', read: true },
]

export const MOCK_VIDEOS = [
  {
    id: 1,
    title: 'Hiragana Complete',
    duration: '32:45',
    level: 'N5',
    views: 1240,
    thumb: 'HG',
    category: 'Writing System',
    date: '2024-09-01',
    embedUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
  },
  {
    id: 2,
    title: 'Katakana Complete',
    duration: '28:12',
    level: 'N5',
    views: 980,
    thumb: 'KT',
    category: 'Writing System',
    date: '2024-09-08',
    embedUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
  },
  {
    id: 3,
    title: 'Basic Sentence Patterns',
    duration: '41:30',
    level: 'N5',
    views: 870,
    thumb: 'BP',
    category: 'Grammar',
    date: '2024-09-15',
    embedUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
  },
  {
    id: 4,
    title: 'て-Form (te-form) Mastery',
    duration: '38:20',
    level: 'N4',
    views: 740,
    thumb: 'TF',
    category: 'Grammar',
    date: '2024-10-01',
    embedUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
  },
  {
    id: 5,
    title: 'Passive Voice in Japanese',
    duration: '35:00',
    level: 'N3',
    views: 620,
    thumb: 'PV',
    category: 'Grammar',
    date: '2024-11-01',
    embedUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
  },
  {
    id: 6,
    title: 'Keigo — Formal Japanese',
    duration: '52:10',
    level: 'N2',
    views: 480,
    thumb: 'KG',
    category: 'Business',
    date: '2024-12-01',
    embedUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
  },
  {
    id: 7,
    title: 'JLPT N3 Reading Strategies',
    duration: '44:55',
    level: 'N3',
    views: 560,
    thumb: 'RS',
    category: 'Exam Prep',
    date: '2025-01-05',
    embedUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
  },
  {
    id: 8,
    title: 'Listening Practice — N4 Level',
    duration: '29:40',
    level: 'N4',
    views: 690,
    thumb: 'LP',
    category: 'Listening',
    date: '2025-01-15',
    embedUrl: 'https://www.youtube-nocookie.com/embed/dQw4w9WgXcQ',
  },
]

export const MOCK_DOWNLOADS = [
  {
    id: 1,
    name: 'JLPT N5 Complete Vocabulary List',
    type: 'PDF',
    size: '2.4 MB',
    level: 'N5',
    date: '2025-01-10',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  {
    id: 2,
    name: 'JLPT N4 Grammar Reference',
    type: 'PDF',
    size: '3.1 MB',
    level: 'N4',
    date: '2025-01-10',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  {
    id: 3,
    name: 'JLPT N3 Kanji Workbook',
    type: 'PDF',
    size: '4.8 MB',
    level: 'N3',
    date: '2025-01-15',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  {
    id: 4,
    name: 'N5 Practice Test — Set 1',
    type: 'PDF',
    size: '1.2 MB',
    level: 'N5',
    date: '2025-02-01',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  {
    id: 5,
    name: 'N4 Practice Test — Set 1',
    type: 'PDF',
    size: '1.5 MB',
    level: 'N4',
    date: '2025-02-01',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  {
    id: 6,
    name: 'N3 Past Paper 2023 (Dec)',
    type: 'PDF',
    size: '2.8 MB',
    level: 'N3',
    date: '2025-02-05',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  {
    id: 7,
    name: 'Hiragana & Katakana Chart',
    type: 'PDF',
    size: '0.8 MB',
    level: 'N5',
    date: '2025-01-01',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  {
    id: 8,
    name: 'Interview Preparation Guide',
    type: 'PDF',
    size: '1.9 MB',
    level: 'All',
    date: '2025-03-01',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  {
    id: 9,
    name: 'Visa Application Checklist',
    type: 'PDF',
    size: '0.5 MB',
    level: 'All',
    date: '2025-03-01',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
  {
    id: 10,
    name: 'CDL Japanese Vocabulary Set',
    type: 'PDF',
    size: '1.3 MB',
    level: 'Special',
    date: '2025-02-20',
    url: 'https://www.w3.org/WAI/ER/tests/xhtml/testfiles/resources/pdf/dummy.pdf',
  },
]

export const MOCK_QUESTIONS = [
  // N5 Vocabulary
  { id: 1, level: 'N5', category: 'Vocabulary', question: 'What does 「学校」(がっこう) mean?', options: ['Hospital', 'School', 'Library', 'Office'], answer: 1 },
  { id: 2, level: 'N5', category: 'Vocabulary', question: 'Choose the correct reading of 「山」', options: ['うみ', 'かわ', 'やま', 'そら'], answer: 2 },
  { id: 3, level: 'N5', category: 'Grammar', question: 'Complete: 「私は毎日学校___行きます」', options: ['が', 'に', 'で', 'を'], answer: 1 },
  { id: 4, level: 'N5', category: 'Grammar', question: '「これは何ですか」— What does this mean?', options: ['Where is this?', 'When is this?', 'What is this?', 'Who is this?'], answer: 2 },
  { id: 5, level: 'N4', category: 'Grammar', question: 'てform of「食べる」is:', options: ['食べて', '食べた', '食べる', '食べます'], answer: 0 },
  { id: 6, level: 'N4', category: 'Vocabulary', question: '「返す」(かえす) means:', options: ['To go home', 'To return (something)', 'To come back', 'To call back'], answer: 1 },
  { id: 7, level: 'N3', category: 'Grammar', question: 'Passive form of 「食べる」:', options: ['食べられる', '食べさせる', '食べてもらう', '食べてある'], answer: 0 },
  { id: 8, level: 'N3', category: 'Vocabulary', question: '「賛成」(さんせい) means:', options: ['Opposition', 'Agreement', 'Problem', 'Solution'], answer: 1 },
]

export const PROGRESS_CHART_DATA = [
  { month: 'Sep', score: 22 },
  { month: 'Oct', score: 38 },
  { month: 'Nov', score: 45 },
  { month: 'Dec', score: 55 },
  { month: 'Jan', score: 61 },
  { month: 'Feb', score: 64 },
]

export const ENROLLMENT_CHART_DATA = [
  { month: 'Sep', count: 24 },
  { month: 'Oct', count: 31 },
  { month: 'Nov', count: 18 },
  { month: 'Dec', count: 12 },
  { month: 'Jan', count: 38 },
  { month: 'Feb', count: 42 },
  { month: 'Mar', count: 29 },
]
